{
 "title": "Individual Movie",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "movie",
    "label": "movie",
    "query": "SELECT title FROM movies\norder by popularity desc"
   },
   {
    "name": "overview",
    "label": "overview",
    "query": "select overview from movies\nwhere title = '$movie'"
   },
   {
    "name": "backdropPath",
    "label": "backdropPath",
    "query": "select backdrop_path from movies\nwhere title = '$movie'"
   },
   {
    "name": "runtime",
    "label": "runtime",
    "query": "select runtime from movies\nwhere title = '$movie'"
   },
   {
    "name": "release_date",
    "label": "release_date",
    "query": "select release_date from movies \nwhere title = '$movie'"
   },
   {
    "name": "revenue",
    "label": "revenue",
    "query": "select revenue from movies\nwhere title = '$movie'"
   },
   {
    "name": "tagline",
    "label": "tagline",
    "query": "select tagline from movies\nwhere title = '$movie'"
   },
   {
    "name": "genres",
    "label": "genres",
    "query": "with movie_genre as (\nselect * from movie_genres\ninner join movies \non movie_id = id\nand title = '$movie'\n) select name\nfrom movie_genre mv\ninner join genres g\non mv.genre_id = g.id "
   },
   {
    "name": "actors",
    "label": "actors",
    "query": "with movie_characters as  (\n\tselect actor_id, character\n\tfrom \n\tactor_characters ac\n\tinner join movies m\n\ton ac.movie_id = m.id \n\tand title = '$movie'\n)\nselect name\nfrom movie_characters mc\ninner join actors a\non mc.actor_id = a.id\norder by id"
   },
   {
    "name": "actor_images",
    "label": "actor_images",
    "query": "with movie_characters as  (\n\tselect actor_id, character\n\tfrom \n\tactor_characters ac\n\tinner join movies m\n\ton ac.movie_id = m.id \n\tand title = '$movie'\n)\nselect CONCAT('https://image.tmdb.org/t/p/w500/', profile_path)\nfrom movie_characters mc\ninner join actors a\non mc.actor_id = a.id\norder by id"
   },
   {
    "name": "characters",
    "label": "characters",
    "query": "with movie_characters as  (\n\tselect actor_id, character\n\tfrom \n\tactor_characters ac\n\tinner join movies m\n\ton ac.movie_id = m.id \n\tand title = '$movie'\n)\nselect character\nfrom movie_characters mc\ninner join actors a\non mc.actor_id = a.id\norder by id"
   },
   {
    "name": "imdbRating",
    "label": "imdbRating",
    "query": "select imdbrating from movies\nwhere title = '$movie'"
   },
   {
    "name": "imdbRatingCount",
    "label": "imdbRatingCount",
    "query": "select imdbratingcount from movies\nwhere title = '$movie'"
   }
  ]
 },
 "panels": [
  {
   "title": "Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select budget from movies\r\nwhere title = '$movie'"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select revenue from movies\r\nwhere title = '$movie'"
    }
   ]
  },
  {
   "title": "Actors",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "with movie_characters as  (\r\n\tselect actor_id, character\r\n\tfrom \r\n\tactor_characters ac\r\n\tinner join movies m\r\n\ton ac.movie_id = m.id \r\n\tand title = '$movie'\r\n)\r\nselect name, character\r\nfrom movie_characters mc\r\ninner join actors a\r\non mc.actor_id = a.id\r\norder by id"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 5 },
   "options": {
    "content": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>${movie} Overview</title>\n</head>\n<body>\n    <h1>Overview</h1>\n    <p>${overview}</p>\n\n    <p><strong>Tagline:</strong> ${tagline}</p>\n    <p><strong>Runtime:</strong> ${runtime} minutes</p>\n    <p><strong>Genres:</strong> ${genres}</p>\n    <p><strong>IMDB Rating:</strong> ${imdbRating} (${imdbRatingCount})</p>\n\n    <div>\n        <img src=\"https://image.tmdb.org/t/p/w500/${backdropPath}\" alt=\"${movie} poster\">\n    </div>\n</body>\n</html>\n"
   }
  }
 ]
}