services:
  movies_metadata:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moviesMetadata
    ports:
      - "5432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init/:/docker-entrypoint-initdb.d/

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  db_data:   
  grafana-data:
