version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moviesMetadata
    ports:
      - "5432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:   